name: Echo workflow
on:
  push:
    branches:
      - main

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "Hello, World!" > message.txt
      - name: Print current directory
        run: |
          pwd
      - name: Print message.txt content
        run: |
          cat message.txt
      - name: Custom message
        run: |
          echo "This is working"
